export const HARD_SKILLS = [
  "accessibility",
  "adobe analytics",
  "agile",
  "airflow",
  "amazon web services",
  "analytics",
  "android",
  "angular",
  "api",
  "apis",
  "automation",
  "aws",
  "azure",
  "bigquery",
  "business intelligence",
  "c++",
  "ci/cd",
  "cloud",
  "css",
  "dashboard",
  "data analysis",
  "data engineering",
  "data modeling",
  "data visualization",
  "dbt",
  "docker",
  "etl",
  "excel",
  "figma",
  "flask",
  "gcp",
  "git",
  "graphql",
  "html",
  "ios",
  "java",
  "javascript",
  "jira",
  "kafka",
  "kubernetes",
  "looker",
  "machine learning",
  "marketing analytics",
  "microservices",
  "mongodb",
  "node",
  "node.js",
  "nosql",
  "postgresql",
  "power bi",
  "product management",
  "python",
  "pytorch",
  "react",
  "redux",
  "rest",
  "roadmap",
  "salesforce",
  "scala",
  "scikit-learn",
  "seo",
  "snowflake",
  "spark",
  "sql",
  "tableau",
  "tensorflow",
  "typescript",
  "ui",
  "ux",
  "user research",
  "vue",
];

export const SOFT_SKILLS = [
  "analytical thinking",
  "collaboration",
  "communication",
  "cross-functional",
  "customer empathy",
  "leadership",
  "mentoring",
  "ownership",
  "problem solving",
  "stakeholder management",
  "strategic planning",
  "teamwork",
];

export const EDUCATION_TERMS = [
  "associate",
  "bachelor",
  "bs",
  "ba",
  "master",
  "ms",
  "mba",
  "phd",
  "degree",
  "certification",
  "certified",
  "gpa",
];

export const ACTION_VERBS = [
  "accelerated",
  "achieved",
  "analyzed",
  "architected",
  "automated",
  "built",
  "collaborated",
  "created",
  "cut",
  "delivered",
  "designed",
  "developed",
  "drove",
  "enabled",
  "engineered",
  "established",
  "expanded",
  "improved",
  "increased",
  "launched",
  "led",
  "managed",
  "migrated",
  "optimized",
  "owned",
  "reduced",
  "shipped",
  "streamlined",
  "validated",
];

export const WEAK_PHRASES = [
  "responsible for",
  "worked on",
  "helped with",
  "assisted with",
  "participated in",
  "duties included",
  "hard worker",
  "team player",
  "go getter",
  "detail oriented",
  "results driven",
];

export const STANDARD_SECTIONS = [
  {
    key: "summary",
    label: "Summary",
    aliases: ["summary", "profile", "professional summary", "objective"],
  },
  {
    key: "skills",
    label: "Skills",
    aliases: ["skills", "technical skills", "core competencies", "technologies"],
  },
  {
    key: "experience",
    label: "Experience",
    aliases: [
      "experience",
      "work experience",
      "professional experience",
      "employment",
      "relevant experience",
    ],
  },
  {
    key: "education",
    label: "Education",
    aliases: ["education", "academic background", "academics"],
  },
  {
    key: "projects",
    label: "Projects",
    aliases: ["projects", "selected projects", "academic projects"],
  },
];
